version: "3.3"

services:
  serial_bridge:
    build:
      context: .
    command:
      - roslaunch
      - robot_platform
      - robot_platform.launch
    network_mode: host
    privileged: true
    devices:
      - "/dev/serial/by-id/usb-Teensyduino_USB_Serial_13671670-if00:/dev/serial/by-id/usb-Teensyduino_USB_Serial_13671670-if00"