version: "3.3"

services:
  ros:
    build:
      context: .
    command:
      - roslaunch
      - robot_platform
      - robot_platform.launch
    network_mode: host
    privileged: true
    devices:
      - /dev:/dev