version: "3.3"

services:
  ros:
    build:
      context: .
    command:
      - roslaunch
      - robot_platform
      - robot_platform.launch
    network_mode: host
    privileged: true
    devices:
      - /dev/serial/by-id/usb-Teensyduino_USB_Serial_13671670-if00:/dev/serial/by-id/usb-Teensyduino_USB_Serial_13671670-if00
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0