---
- name: OpenVPN Server
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
    # - name: inventory_hostname
    #   debug:
    #     var: inventory_hostname
    #   tags: debug_info
    
    - name: Include global variables
      ansible.builtin.include_vars:
        file: site.yml
      
    - name: Install OpenVPN Server
      ansible.builtin.include_role:
        name: openvpn

