---

- name: "Install curl binary"
  ansible.builtin.package:
    name: curl
    state: present

- name: Install OpenVPN source-list gpg key
  ansible.builtin.shell:
    cmd: mkdir -p /etc/apt/keyrings && curl -fsSL https://swupdate.openvpn.net/repos/repo-public.gpg | gpg --dearmor > /etc/apt/keyrings/openvpn-repo-public.gpg
    creates: /etc/apt/keyrings/openvpn-repo-public.gpg

- name: Install OpenVPN source-list
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/openvpn-repo-public.gpg] https://build.openvpn.net/debian/openvpn/release/{{ openvpn_version }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes


- name: "Setup OpenVPN server"
  ansible.builtin.include_tasks:
    file: server.yml
  when: vpn_master_hostname == inventory_hostname

- name: "Setup OpenVPN clients"
  ansible.builtin.include_tasks:
    file: client.yml
  when: vpn_master_hostname != inventory_hostname
